/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : 127nmyp
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : NMYP

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2024-04-26 17:24:35
*/


-- ----------------------------
-- Table structure for BASE_DRUG_INFO
-- ----------------------------
DROP TABLE "NMYP"."BASE_DRUG_INFO";
CREATE TABLE "NMYP"."BASE_DRUG_INFO" (
"DRUG_CODE" VARCHAR2(50 BYTE) NOT NULL ,
"PUBON_LN_RSLT_ID" VARCHAR2(50 BYTE) NULL ,
"DRUG_NAME" VARCHAR2(255 BYTE) NULL ,
"DOSFORM_NAME" VARCHAR2(100 BYTE) NULL ,
"SPEC_NAME" VARCHAR2(255 BYTE) NULL ,
"CONVRAT" VARCHAR2(4 BYTE) NULL ,
"PAC" VARCHAR2(200 BYTE) NULL ,
"PACMATL" VARCHAR2(200 BYTE) NULL ,
"PUBONLN_PRIC" NUMBER(18,2) NULL ,
"PRODENTP_NAME" VARCHAR2(200 BYTE) NULL ,
"DCLA_ENTP_NAME" VARCHAR2(200 BYTE) NULL ,
"BAS_MEDN_FLAG" VARCHAR2(3 BYTE) NULL ,
"TENDITM_NAME" VARCHAR2(100 BYTE) NULL ,
"PUBONLN_STAS" VARCHAR2(5 BYTE) NULL ,
"PUBONLN_TIME" DATE NULL ,
"PURC_PROD_TYPE" VARCHAR2(255 BYTE) NULL ,
"SPARE" VARCHAR2(255 BYTE) NULL ,
"PROD_SOUC_VAL" VARCHAR2(255 BYTE) NULL ,
"CONSEVAL_DRUG" VARCHAR2(255 BYTE) NULL ,
"APRVNO" VARCHAR2(100 BYTE) NULL ,
"UPDT_TIME" DATE NULL ,
"MINUNT_NAME" VARCHAR2(255 BYTE) NULL ,
"DCLA_ENTP_CODE" VARCHAR2(255 BYTE) NULL ,
"MINPACUNT_NAME" VARCHAR2(255 BYTE) NULL ,
"PRODENTP_CODE" VARCHAR2(255 BYTE) NULL ,
"PUBONLN_RSLT_ID" VARCHAR2(255 BYTE) NULL ,
"TENDITM_ID" VARCHAR2(255 BYTE) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "NMYP"."BASE_DRUG_INFO" IS '挂网药品信息';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."DRUG_CODE" IS '药品统一编码';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PUBON_LN_RSLT_ID" IS '挂网产品 ID';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."DRUG_NAME" IS '产品名称';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."DOSFORM_NAME" IS '剂型';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."SPEC_NAME" IS '规格';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."CONVRAT" IS '转换比';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PAC" IS '包装';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PACMATL" IS '包装材质';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PUBONLN_PRIC" IS '挂网价';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PRODENTP_NAME" IS '生产企业';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."DCLA_ENTP_NAME" IS '代理企业';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."BAS_MEDN_FLAG" IS '基药属性 0：否 1：是';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."TENDITM_NAME" IS '项目名称';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PUBONLN_STAS" IS '挂网状态 0：未挂网1：已挂网';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PUBONLN_TIME" IS '挂网时间';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PURC_PROD_TYPE" IS '带量批次';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."SPARE" IS '是否集采备选';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."PROD_SOUC_VAL" IS '产品来源';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."CONSEVAL_DRUG" IS '仿制药一致性评价药品 0：否1：是';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."APRVNO" IS '批准文号';
COMMENT ON COLUMN "NMYP"."BASE_DRUG_INFO"."UPDT_TIME" IS '最后更新时间';

-- ----------------------------
-- Indexes structure for table BASE_DRUG_INFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table BASE_DRUG_INFO
-- ----------------------------
ALTER TABLE "NMYP"."BASE_DRUG_INFO" ADD CHECK ("DRUG_CODE" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table BASE_DRUG_INFO
-- ----------------------------
ALTER TABLE "NMYP"."BASE_DRUG_INFO" ADD PRIMARY KEY ("DRUG_CODE");
