
-- ----------------------------
-- Table structure for BASE_COMPANY_INFO
-- ----------------------------
DROP TABLE "NMYP"."BASE_COMPANY_INFO";
CREATE TABLE "NMYP"."BASE_COMPANY_INFO" (
"ORG_INFO_ID" VARCHAR2(50 BYTE) NOT NULL ,
"USCC" VARCHAR2(50 BYTE) NULL ,
"ENTP_CODE" VARCHAR2(100 BYTE) NULL ,
"ORG_NAME" VARCHAR2(255 BYTE) NULL ,
"ORG_TYPE_CODE" VARCHAR2(3 BYTE) NULL ,
"CONER" VARCHAR2(255 BYTE) NULL ,
"CONER_MOD" VARCHAR2(255 BYTE) NULL ,
"FIX_TEL" VARCHAR2(50 BYTE) NULL ,
"UPDT_TIME" DATE NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "NMYP"."BASE_COMPANY_INFO" IS ''企业信息'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."ORG_INFO_ID" IS ''组织信息 ID'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."USCC" IS ''统一社会信用代码'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."ENTP_CODE" IS ''企业代码'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."ORG_NAME" IS ''生产企业'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."ORG_TYPE_CODE" IS ''企业类型'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."CONER" IS ''联系人'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."CONER_MOD" IS ''联系电话'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."FIX_TEL" IS ''固定电话'';
COMMENT ON COLUMN "NMYP"."BASE_COMPANY_INFO"."UPDT_TIME" IS ''最后一次更新时间'';

-- ----------------------------
-- Indexes structure for table BASE_COMPANY_INFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table BASE_COMPANY_INFO
-- ----------------------------
ALTER TABLE "NMYP"."BASE_COMPANY_INFO" ADD CHECK ("ORG_INFO_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table BASE_COMPANY_INFO
-- ----------------------------
ALTER TABLE "NMYP"."BASE_COMPANY_INFO" ADD PRIMARY KEY ("ORG_INFO_ID");
