/*
 Navicat Premium Data Transfer

 Source Server         : nmyp
 Source Server Type    : Oracle
 Source Server Version : 110200 (Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options)
 Source Host           : 127.0.0.1:1521
 Source Schema         : NMYP

 Target Server Type    : Oracle
 Target Server Version : 110200 (Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options)
 File Encoding         : 65001

 Date: 23/04/2024 21:32:37
*/


-- ----------------------------
-- Table structure for MIDDLE_PURCHASE_ORDER
-- ----------------------------
-- DROP TABLE "NMYP"."MIDDLE_PURCHASE_ORDER";
CREATE TABLE "NMYP"."MIDDLE_PURCHASE_ORDER" (
  "ID" VARCHAR2(50 BYTE) NOT NULL,
  "ORD_ID" VARCHAR2(50 BYTE),
  "ORD_CODE" VARCHAR2(50 BYTE),
  "ORD_DETL_ID" VARCHAR2(50 BYTE),
  "SHP_ID" VARCHAR2(50 BYTE),
  "PUBONLN_PRIC" NUMBER(18,2),
  "PURCPRIC" NUMBER(18,2),
  "PURC_CNT" NUMBER(11,0),
  "DELVENTP_CODE" VARCHAR2(100 BYTE),
  "DELVENTP_NAME" VARCHAR2(100 BYTE),
  "SEND_TIME" DATE,
  "MEDINS_CODE" VARCHAR2(50 BYTE),
  "MEDINS_NAME" VARCHAR2(100 BYTE),
  "RESPONSE_STATUS" VARCHAR2(3 BYTE),
  "ADDR_NAME" VARCHAR2(100 BYTE),
  "CON_NAME" VARCHAR2(50 BYTE),
  "CON_TEL" VARCHAR2(50 BYTE),
  "MEMO" VARCHAR2(255 BYTE),
  "DOCMKER" VARCHAR2(100 BYTE),
  "DRUG_INFO_ID" VARCHAR2(50 BYTE),
  "PROD_CODE" VARCHAR2(50 BYTE),
  "PRODENTP_NAME" VARCHAR2(255 BYTE),
  "PRODENTP_CODE" VARCHAR2(50 BYTE),
  "DCLA_ENTP_NAME" VARCHAR2(255 BYTE),
  "DCLA_ENTP_CODE" VARCHAR2(50 BYTE),
  "DOSFORM" VARCHAR2(255 BYTE),
  "PROD_SPEC" VARCHAR2(255 BYTE),
  "PROD_PAC" VARCHAR2(255 BYTE),
  "PROD_BIG_PAC" VARCHAR2(255 BYTE),
  "PAC_MATL" VARCHAR2(255 BYTE),
  "MOL" VARCHAR2(255 BYTE),
  "PROD_MATL" VARCHAR2(255 BYTE),
  "PROD_PAC_MATL" VARCHAR2(255 BYTE),
  "APRVNO" VARCHAR2(255 BYTE),
  "SHP_STAS" VARCHAR2(3 BYTE),
  "SHP_STAS_VAL" VARCHAR2(255 BYTE),
  "SHP_MEMO" VARCHAR2(255 BYTE),
  "SHP_PRIC" NUMBER(18,2),
  "SHP_CNT" NUMBER(8,0),
  "SHP_AMT" NUMBER(18,2),
  "SHPP_CNT" NUMBER(8,0),
  "SHPP_AMT" NUMBER(18,2),
  "CNCL_TYPE" VARCHAR2(3 BYTE),
  "CNCL_TYPE_VAL" VARCHAR2(50 BYTE),
  "PROD_NAME" VARCHAR2(200 BYTE),
  "ORD_DETL_COUNT" NUMBER(8,0),
  "ADDR_ID" VARCHAR2(50 BYTE),
  "PUBONLN_RSLT_ID" VARCHAR2(50 BYTE),
  "STROOM_NAME" VARCHAR2(255 BYTE),
  "ORD_DETL_STAS" VARCHAR2(255 BYTE),
  "PURC_AMT" NUMBER(18,2),
  "ORD_SUMAMT" NUMBER(18,2),
  "ORD_DETL_MEMO" VARCHAR2(255 BYTE),
  "READ_FLAG" VARCHAR2(1 BYTE),
  "READ_TIME" DATE,
  "AVL_SHP_CNT" NUMBER(18,2),
  "EXPY_ENDTIME" DATE,
  "RETN_LIST" VARCHAR2(255 BYTE),
  "PUB_ONLINE_PRIC" NUMBER(18,2),
  "RETN_INVO" VARCHAR2(255 BYTE),
  "SHP_TIME" DATE,
  "INVO_AMT" NUMBER(18,2),
  "SEL_INVO_TWO" VARCHAR2(255 BYTE),
  "ITEMNAME" VARCHAR2(255 BYTE),
  "SEL_INVO_ONE" VARCHAR2(255 BYTE),
  "PUBONLN_DELV_EXT_ID" VARCHAR2(255 BYTE),
  "RTNB_CNT" NUMBER(18,2),
  "CRTER_NAME" VARCHAR2(255 BYTE),
  "PLAN_DETL_MEMO" VARCHAR2(255 BYTE),
  "SEL_LIST" VARCHAR2(255 BYTE),
  "RETN_CNT" NUMBER(18,2),
  "HIGH_SEL_LMTPRIC" VARCHAR2(50 BYTE),
  "SHPP_PRIC" NUMBER(18,2),
  "PURC_PLAN_CODE" VARCHAR2(255 BYTE),
  "HI_PAY_PRIC" NUMBER(18,2),
  "SEL_INVO_SCD" VARCHAR2(255 BYTE),
  "OUTSTO_STAS" VARCHAR2(50 BYTE),
  "PLAN_MEMO" VARCHAR2(255 BYTE),
  "MANU_LOTNUM" VARCHAR2(255 BYTE),
  "RPUP_CNT_FLAG" VARCHAR2(255 BYTE),
  "RTND_CNT" NUMBER(18,4),
  "SHP_CODE" VARCHAR2(255 BYTE),
  "OUTSTO_STAS_VAL" VARCHAR2(255 BYTE),
  "PROD_ATTRS" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ORD_ID" IS '订单 ID';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ORD_CODE" IS '订单 CODE';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ORD_DETL_ID" IS '订单明细 ID';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHP_ID" IS '发货 ID';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PUBONLN_PRIC" IS '挂网价格';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PURCPRIC" IS '采购价格';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PURC_CNT" IS '采购数量';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."DELVENTP_CODE" IS '配送企业编码';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."DELVENTP_NAME" IS '配送企业名称';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SEND_TIME" IS '订单发送时间';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."MEDINS_CODE" IS '医疗机构唯一';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."MEDINS_NAME" IS '医疗机构名称';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."RESPONSE_STATUS" IS '订单响应状态 0：待响应 1：已响应 2：拒绝响应';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ADDR_NAME" IS '收货地址';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."CON_NAME" IS '收货人';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."CON_TEL" IS '收货人电话';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."MEMO" IS '下单备注';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."DOCMKER" IS '制单人';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."DRUG_INFO_ID" IS '产品 ID 老系统的产品id可能为空';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PROD_CODE" IS '药品统一编码';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PRODENTP_NAME" IS '生产企业名称';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PRODENTP_CODE" IS '生产企业编码';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."DCLA_ENTP_NAME" IS '申报企业名称';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."DCLA_ENTP_CODE" IS '申报企业编码';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."DOSFORM" IS '剂型';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PROD_SPEC" IS '规格';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PROD_PAC" IS '包装';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PROD_BIG_PAC" IS '大包装';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PAC_MATL" IS '包材';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."MOL" IS '型号';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PROD_MATL" IS '产品材质';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PROD_PAC_MATL" IS '产品包装材质';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."APRVNO" IS '批准文号(注册证编号)';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHP_STAS" IS '发货明细状态 1:待发货 2：已发货 3：已收货 4：已作废';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHP_STAS_VAL" IS '订单明细状态中文';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHP_MEMO" IS '发货备注';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHP_PRIC" IS '发货价格';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHP_CNT" IS '发货数量';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHP_AMT" IS '发货总金额';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHPP_CNT" IS '收货数量';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."SHPP_AMT" IS '收货总金额';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."CNCL_TYPE" IS '作废类型 1：医疗机构主动作废 2：配送企业超7日未发货 3：补录单作废';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."CNCL_TYPE_VAL" IS '作废类型注释';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PROD_NAME" IS '产品名称';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ORD_DETL_COUNT" IS '订单明细数量';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ADDR_ID" IS '配送地址 ID';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PUBONLN_RSLT_ID" IS '药品挂网结果ID';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."STROOM_NAME" IS '库房名称';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ORD_DETL_STAS" IS '订单明细状态 1待发货 2全部发货 3部分发货 4缺货 5作废';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."PURC_AMT" IS '订单金额';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ORD_SUMAMT" IS '订单总单金额';
COMMENT ON COLUMN "NMYP"."MIDDLE_PURCHASE_ORDER"."ORD_DETL_MEMO" IS '订单明细备注';
COMMENT ON TABLE "NMYP"."MIDDLE_PURCHASE_ORDER" IS '采购订单信息';

-- ----------------------------
-- Primary Key structure for table MIDDLE_PURCHASE_ORDER
-- ----------------------------
ALTER TABLE "NMYP"."MIDDLE_PURCHASE_ORDER" ADD CONSTRAINT "SYS_C0011479" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table MIDDLE_PURCHASE_ORDER
-- ----------------------------
ALTER TABLE "NMYP"."MIDDLE_PURCHASE_ORDER" ADD CONSTRAINT "SYS_C0011487" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
