/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.1.0

Source Server         : 127nmyp
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : NMYP

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2024-04-25 14:17:01
*/


-- ----------------------------
-- Table structure for MIDDLE_ORDER_SHP
-- ----------------------------
-- DROP TABLE "NMYP"."MIDDLE_ORDER_SHP";
CREATE TABLE "NMYP"."MIDDLE_ORDER_SHP" (
"SHP_ID" VARCHAR2(50 BYTE) NOT NULL ,
"ORD_CODE" VARCHAR2(50 BYTE) NULL ,
"PROD_NAME" VARCHAR2(100 BYTE) NULL ,
"DOSFORM" VARCHAR2(100 BYTE) NULL ,
"PROD_SPEC" VARCHAR2(100 BYTE) NULL ,
"PROD_PAC" VARCHAR2(255 BYTE) NULL ,
"PRODENTP_NAME" VARCHAR2(100 BYTE) NULL ,
"MEDINS_NAME" VARCHAR2(100 BYTE) NULL ,
"PURCPRIC" NUMBER(18,4) NULL ,
"PURC_CNT" NUMBER(18) NULL ,
"SHP_CNT" NUMBER(18) NULL ,
"SHPP_CNT" NUMBER(18,2) NULL ,
"PURC_AMT" NUMBER(18,4) NULL ,
"SHP_AMT" NUMBER(18,2) NULL ,
"SHPP_AMT" NUMBER(18,4) NULL ,
"PUBONLN_PRIC" NUMBER(18,2) NULL ,
"SEND_TIME" DATE NULL ,
"READ_TIME" DATE NULL ,
"PLAN_DETL_MEMO" VARCHAR2(100 BYTE) NULL ,
"PROD_CODE" VARCHAR2(100 BYTE) NULL ,
"SHP_STAS" VARCHAR2(3 BYTE) NULL ,
"ORD_DETL_ID" VARCHAR2(50 BYTE) NULL ,
"ADDR_ID" VARCHAR2(50 BYTE) NULL ,
"ADDR" VARCHAR2(255 BYTE) NULL ,
"SEL_INVO_ONE" VARCHAR2(255 BYTE) NULL ,
"SEL_INVO_SCD" VARCHAR2(255 BYTE) NULL ,
"MANU_LOTNUM" VARCHAR2(100 BYTE) NULL ,
"EXPY_ENDTIME" DATE NULL ,


"ITEM_CODG" VARCHAR2(255 BYTE) NULL ,
"TWO_INFONO" VARCHAR2(255 BYTE) NULL ,
"HOSP_LIST_ID" VARCHAR2(255 BYTE) NULL ,
"ESSDRUG_TYPE" VARCHAR2(255 BYTE) NULL ,
"MINUNT_NAME" VARCHAR2(255 BYTE) NULL ,
"DELVENTP_CODE" VARCHAR2(255 BYTE) NULL ,
"SHP_TIME" DATE NULL ,
"SHPP_TIME" DATE NULL ,
"MINPACUNT_NAME" VARCHAR2(255 BYTE) NULL ,
"ITEMNAME" VARCHAR2(255 BYTE) NULL ,
"SHP_MEMO" VARCHAR2(255 BYTE) NULL ,
"RTNB_CNT" NUMBER(18,2) NULL ,
"PROD_TYPE" VARCHAR2(255 BYTE) NULL ,
"SEL_LIST" VARCHAR2(255 BYTE) NULL ,
"CONVRAT" VARCHAR2(255 BYTE) NULL ,
"RETN_CNT" NUMBER(18,2) NULL ,
"PROD_ID" VARCHAR2(255 BYTE) NULL ,
"APRVNO" VARCHAR2(255 BYTE) NULL ,
"DCLA_ENTP_CODE" VARCHAR2(255 BYTE) NULL ,
"SHP_CODE" VARCHAR2(255 BYTE) NULL ,
"SPLM_FLAG" VARCHAR2(255 BYTE) NULL ,
"DELVENTP_NAME" VARCHAR2(255 BYTE) NULL ,
"PACMATL" VARCHAR2(255 BYTE) NULL ,
"DCLA_ENTP_NAME" VARCHAR2(255 BYTE) NULL ,
"HOSP_BIDPRCU_ITEM_ID" VARCHAR2(255 BYTE) NULL ,
"MEDINS_CODE" VARCHAR2(255 BYTE) NULL

)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "NMYP"."MIDDLE_ORDER_SHP" IS '药品获取收货信息';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SHP_ID" IS '发货明细Id';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."ORD_CODE" IS '订单编码';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PROD_NAME" IS '产品名称';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."DOSFORM" IS '剂型';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PROD_SPEC" IS '规格';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PROD_PAC" IS '包装';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PRODENTP_NAME" IS '生产企业';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."MEDINS_NAME" IS '医疗机构';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PURCPRIC" IS '医院采购价（元）';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PURC_CNT" IS '采购数量';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SHP_CNT" IS '发货数量';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SHPP_CNT" IS '收货数量';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PURC_AMT" IS '采购金额（元）';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SHP_AMT" IS '发货金额（元）';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SHPP_AMT" IS '收货金额（元）';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PUBONLN_PRIC" IS '挂网价（元）';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SEND_TIME" IS '发送时间';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."READ_TIME" IS '阅读时间';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PLAN_DETL_MEMO" IS '备注';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."PROD_CODE" IS '药品统一编码';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SHP_STAS" IS '订单发货状态 订单发货状态 1.待发货 2.已发货 3.已收货 4已作废';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."ORD_DETL_ID" IS '订单明细ID';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."ADDR_ID" IS '配送地址ID';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."ADDR" IS '配送地址';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SEL_INVO_ONE" IS '一票发票号 多个发票号逗号隔开';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."SEL_INVO_SCD" IS '二票发票号 多个发票号逗号隔开';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."MANU_LOTNUM" IS '生产批号';
COMMENT ON COLUMN "NMYP"."MIDDLE_ORDER_SHP"."EXPY_ENDTIME" IS '有效期';

-- ----------------------------
-- Indexes structure for table MIDDLE_ORDER_SHP
-- ----------------------------

-- ----------------------------
-- Checks structure for table MIDDLE_ORDER_SHP
-- ----------------------------
ALTER TABLE "NMYP"."MIDDLE_ORDER_SHP" ADD CHECK ("SHP_ID" IS NOT NULL);
ALTER TABLE "NMYP"."MIDDLE_ORDER_SHP" ADD CHECK ("SHP_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table MIDDLE_ORDER_SHP
-- ----------------------------
ALTER TABLE "NMYP"."MIDDLE_ORDER_SHP" ADD PRIMARY KEY ("SHP_ID");
