DROP TABLE MIDDLE_PURCHASE_ORDER;
CREATE TABLE MIDDLE_PURCHASE_ORDER (ORD_ID	VARCHAR2(50)	,
ORD_CODE	VARCHAR2(50)	,
ORD_DETL_ID	VARCHAR2(50)	,
SHP_ID	VARCHAR2(50)	,
PUBONLN_PRIC	NUMBER(18,2)	,
PURCPRIC	NUMBER(18,2)	,
PURC_CNT	NUMBER(11,0)	,
DELVENTP_CODE	VARCHAR2(100)	,
DELVENTP_NAME	VARCHAR2(100)	,
SEND_TIME	DATE	,
MEDINS_CODE	VARCHAR2(50)	,
MEDINS_NAME	VARCHAR2(100)	,
RESPONSE_STATUS	VARCHAR2(3)	,
ADDR_NAME	VARCHAR2(50)	,
CON_NAME	VARCHAR2(50)	,
CON_TEL	VARCHAR2(50)	,
MEMO	VARCHAR2(255)	,
DOCMKER	VARCHAR2(50)	,
DRUG_INFO_ID	VARCHAR2(50)	,
PROD_CODE	VARCHAR2(50)	,
PRODENTP_NAME	VARCHAR2(255)	,
PRODENTP_CODE	VARCHAR2(50)	,
DCLA_ENTP_NAME	VARCHAR2(255)	,
DCLA_ENTP_CODE	VARCHAR2(50)	,
DOSFORM	VARCHAR2(255)	,
PROD_SPEC	VARCHAR2(255)	,
PROD_PAC	VARCHAR2(255)	,
PROD_BIG_PAC	VARCHAR2(255)	,
PAC_MATL	VARCHAR2(255)	,
MOL	VARCHAR2(255)	,
PROD_MATL	VARCHAR2(255)	,
PROD_PAC_MATL	VARCHAR2(255)	,
APRVNO	VARCHAR2(255)	,
SHP_STAS	VARCHAR2(3)	,
SHP_STAS_VAL	VARCHAR2(255)	,
SHP_MEMO	VARCHAR2(255)	,
SHP_PRIC	NUMBER(18,2)	,
SHP_CNT	NUMBER(8,0)	,
SHP_AMT	NUMBER(18,2)	,
SHPP_CNT	NUMBER(8,0)	,
SHPP_AMT	NUMBER(18,2)	,
CNCL_TYPE	VARCHAR2(3)	,
CNCL_TYPE_VAL	VARCHAR2(50)	,
PROD_NAME	VARCHAR2(200)	,
ORD_DETL_COUNT	NUMBER(8,0)	,
ADDR_ID	VARCHAR2(50)	,
PUBONLN_RSLT_ID	VARCHAR2(50)	,
STROOM_NAME	VARCHAR2(255)	,
ORD_DETL_STAS	VARCHAR2(255)	,
PURC_AMT	NUMBER(18,2)	,
ORD_SUMAMT	NUMBER(18,2)	,
ORD_DETL_MEMO	VARCHAR2(255)	,
READ_FLAG	VARCHAR2(3)	,
READ_TIME	DATE	);
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ORD_ID IS '订单 ID';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ORD_CODE IS '订单 CODE';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ORD_DETL_ID IS '订单明细 ID';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHP_ID IS '发货 ID';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PUBONLN_PRIC IS '挂网价格';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PURCPRIC IS '采购价格';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PURC_CNT IS '采购数量';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.DELVENTP_CODE IS '配送企业 USCC';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.DELVENTP_NAME IS '配送企业名称';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SEND_TIME IS '订单发送时间';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.MEDINS_CODE IS '医疗机构唯一';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.MEDINS_NAME IS '医疗机构名称';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.RESPONSE_STATUS IS '订单响应状态 0：待响应 1：已响应 2：拒绝响应';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ADDR_NAME IS '收货地址';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.CON_NAME IS '收货人';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.CON_TEL IS '收货人电话';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.MEMO IS '下单备注';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.DOCMKER IS '制单人';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.DRUG_INFO_ID IS '产品 ID 老系统的产品ID可能为空';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PROD_CODE IS '国家唯一编码';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PRODENTP_NAME IS '生产企业名称';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PRODENTP_CODE IS '生产企业 USCC';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.DCLA_ENTP_NAME IS '申报企业名称';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.DCLA_ENTP_CODE IS '申报企业 USCC';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.DOSFORM IS ' 剂型';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PROD_SPEC IS '规格';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PROD_PAC IS '包装';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PROD_BIG_PAC IS '大包装';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PAC_MATL IS '包材';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.MOL IS ' 型号';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PROD_MATL IS '产品材质';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PROD_PAC_MATL IS ' 产品包装材质';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.APRVNO IS '批准文号(注册证编号)';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHP_STAS IS '发货明细状态 1:待发货 2：已发货 3：已收货 4：已作废';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHP_STAS_VAL IS '订单明细状态';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHP_MEMO IS '发货备注';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHP_PRIC IS '发货价格';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHP_CNT IS '发货数量';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHP_AMT IS '发货总金额';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHPP_CNT IS '收货数量';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.SHPP_AMT IS '收货总金额';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.CNCL_TYPE IS '作废类型 1：医疗机构主动作废 2：配送企业超7日未发货 3：补录单作废';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.CNCL_TYPE_VAL IS '作废类型注释';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PROD_NAME IS '产品名称';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ORD_DETL_COUNT IS '订单明细数量';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ADDR_ID IS '配送地址 ID';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PUBONLN_RSLT_ID IS '药品挂网结果';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.STROOM_NAME IS '库房名称';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ORD_DETL_STAS IS '订单明细状态 1待发货 2全部发货 3部分发货 4缺货 5作废';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.PURC_AMT IS '订单金额';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ORD_SUMAMT IS '订单总单金额';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.ORD_DETL_MEMO IS '订单明细备注';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.READ_FLAG IS '是否已读 0未读 1已读';
COMMENT ON COLUMN MIDDLE_PURCHASE_ORDER.READ_TIME IS '订单已读时间';
COMMENT ON TABLE "NMYP"."MIDDLE_PURCHASE_ORDER" IS '订单信息';

drop table MIDDLE_INVOICE_INFO;
CREATE TABLE MIDDLE_INVOICE_INFO(
UUID	VARCHAR2(36)	,
INVO_ID	VARCHAR2(100)	,
INVO_TYPE	VARCHAR2(3)	,
INVO_CODE	VARCHAR2(40)	,
INVONO	VARCHAR2(40)	,
BILL_AMT	NUMBER(18,2)	,
BILL_TIME	DATE	,
INVOTTL	VARCHAR2(50)	,
INVO_MEMO	VARCHAR2(50)	,
RESPONSE_STATE	VARCHAR2(2)	,
RESPONSE_INFO	VARCHAR2(2000)	,
RESPONSE_TIME	DATE
);
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.UUID IS '企业主键';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.INVO_ID IS '发票编号(接口返回)';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.INVO_TYPE IS '发票类型(1：第一票 2：第二票 3：销售清单4：消退清单5：消退发票)';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.INVO_CODE IS '发票代码';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.INVONO IS '发票号';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.BILL_AMT IS '票据金额';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.BILL_TIME IS '开票时间';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.INVOTTL IS '发票抬头';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.INVO_MEMO IS '发票备注';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.RESPONSE_STATE IS '省平台交互状态(0:未交互  2:上传成功  3:上传失败)';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.RESPONSE_INFO IS '省平台交互信息';
COMMENT ON COLUMN MIDDLE_INVOICE_INFO.RESPONSE_TIME IS '省平台交互时间';
COMMENT ON TABLE MIDDLE_INVOICE_INFO IS '发票信息';
ALTER TABLE MIDDLE_INVOICE_INFO ADD CONSTRAINT "MIDDLE_INVOICE_INFO_UUID" PRIMARY KEY ("UUID");

drop table MIDDLE_INVOICE_IMG;
CREATE TABLE MIDDLE_INVOICE_IMG(
UUID	VARCHAR2(36)	,
INVO_ID	VARCHAR2(100)	,
IMG_URL	VARCHAR2(120)	,
FILE_NAME	VARCHAR2(40)	,
FILE_ID	VARCHAR2(200)	,
RESPONSE_STATE	VARCHAR2(2)	,
RESPONSE_INFO	VARCHAR2(2000)	,
RESPONSE_TIME	DATE
);
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.UUID IS '企业主键';
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.INVO_ID IS '发票编号(发票表的INVO_ID)';
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.IMG_URL IS '发票图片地址';
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.FILE_NAME IS '附件名称';
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.FILE_ID IS '省平台返回文件地址';
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.RESPONSE_STATE IS '省平台交互状态(0:未交互  2:上传成功  3:上传失败)';
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.RESPONSE_INFO IS '省平台交互信息';
COMMENT ON COLUMN MIDDLE_INVOICE_IMG.RESPONSE_TIME IS '省平台交互时间';
COMMENT ON TABLE MIDDLE_INVOICE_IMG IS '发票图片信息';
ALTER TABLE MIDDLE_INVOICE_IMG ADD CONSTRAINT "MIDDLE_INVOICE_IMG_UUID" PRIMARY KEY ("UUID");
